### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by tsh11na** [tsh11na/portfolio#9]
- [ ] Add English contents
- [ ] Add photo of myself
- [ ] Update reserach intoductions
